### ISSUE TITLE
Generation of ast visuals

### ISSUE THREAD

**Issue by larsrinn** [emilyemorehouse/ast-and-me#18]
Hi Emily,

great talk, thank you for that. While watching the video from Pycon, I wondered how you generated those AST visuals: https://github.com/emilyemorehouse/ast-and-me/blob/master/img/trees/pre-fold.png

Did you do that manually or come up with some library/script? I found astmonkey https://github.com/mutpy/astmonkey but they are not as pretty as yours.

**Comment by emilyemorehouse** [comment]
Thanks! I used a fork of https://github.com/ivan111/vpyast so I could change the colors 😄

**Comment by larsrinn** [comment]
Ah great, thanks for the quick answer
